export const homeObjOne = {
  alt: "car",
  buttonLabel: "sssGet started",
  buttonLabel2: "",
  buttonLabel3: "",
  buttonLabel4: "",
  buttonLabel5: "",
  buttonLabel6: "",
  dark: true,
  darkText: false,
  description:
    "I spend my time working out, being outdoors and working on personal projects ",
  description2: "",
  description3: "",
  description4: "",
  description5: "",
  description6: "",
  headline: "Adventurous and always looking to expand my skillset",
  id: "about",
  img: "/images/svg-1.svg",
  imgStart: false,
  lightBg: false,
  lightText: true,
  lighttextDesc: true,
  primary: true,
  topLine: "About Me",
  buttonPresent: false,
};

export const homeObjTwo = {
  alt: "Piggybanck",
  buttonLabel: "Learn More",
  buttonLabel2: "",
  buttonLabel3: "",
  buttonLabel4: "",
  buttonLabel5: "",
  buttonLabel6: "",
  dark: false,
  darkText: true,
  description:
    "Handling data. Performing Root Cause Analysis. Tracking Trends and communicating with clients",
  description2: "",
  description3: "",
  description4: "",
  description5: "",
  description6: "",
  headline: "Scientist with 6+ years of experience",
  id: "discover",
  img: "/images/svg-4.svg",
  imgStart: true,
  lightBg: true,
  lightText: false,
  lighttextDesc: false,
  primary: false,
  topLine: "Skills",
  buttonPresent: false,
};

export const homeObjThree = {
  alt: "car",
  buttonLabel: "Start Now",
  buttonLabel2: "",
  buttonLabel3: "",
  buttonLabel4: "",
  buttonLabel5: "",
  buttonLabel6: "",
  dark: false,
  darkText: true,
  description: "B.S. Computer Science, May 2022",
  description2: "M.S. Microbiology and Cell Science, August 2017",
  description3: "B.S. Microbiology and Cell Science, June 2016",
  description4: "",
  description5: "",
  description6: "",
  headline: "My Academic Journey",
  id: "signup",
  img: "/images/svg-3.svg",
  imgStart: false,
  lightBg: true,
  lightText: false,
  lighttextDesc: false,
  primary: false,
  topLine: "Education",
  buttonPresent: false,
};

export const homeObjFour = {
  alt: "car",
  buttonLabel: "Look at the code I used to create this website",
  buttonLabel2:
    "Covid on Flight tracks potential COVID-19 infections during to airline travel",
  buttonLabel3:
    "Initialize this project and play Tic-Tac-Toe against an AI. See how well you do!",
  buttonLabel4:
    "Initialize this project and play a game of Minesweeper set up in C++",
  buttonLabel5: "Upload Images into the project and watch how they combine.",
  buttonLabel6:
    "Initialize this project and interact with Fractals through the GUI",
  dark: true,
  darkText: false,
  description: "",
  description2: "",
  description3: "",
  description4: "",
  description5: "",
  description6: "",
  headline: "A Few Selected Projects",
  id: "services",
  img: "/images/svg-5.svg",
  imgStart: false,
  lightBg: false,
  lightText: true,
  lighttextDesc: true,
  primary: true,
  topLine: "Portfolio",
  buttonPresent: true,
};
