export const homeObjOne = {
  alt: "car",
  buttonLabel: "sssGet started",
  dark: true,
  darkText: false,
  description:
    "I spend my time working out, being outdoors and working on personal projects ",
  description2: "",
  description3: "",
  headline: "Adventurous and always looking to expand my skillset",
  id: "about",
  img: "/images/svg-1.svg",
  imgStart: false,
  lightBg: false,
  lightText: true,
  lighttextDesc: true,
  primary: true,
  topLine: "About Me",
};

export const homeObjTwo = {
  alt: "Piggybanck",
  buttonLabel: "Learn More",
  dark: false,
  darkText: true,
  description:
    "Handling data. Performing Root Cause Analysis. Tracking Trends and communicating with clients",
  description2: "",
  description3: "",
  headline: "Scientist with 6+ years of experience",
  id: "discover",
  img: "/images/svg-4.svg",
  imgStart: true,
  lightBg: true,
  lightText: false,
  lighttextDesc: false,
  primary: false,
  topLine: "Skills",
};

export const homeObjThree = {
  alt: "car",
  buttonLabel: "Start Now",
  darkText: true,
  description: "B.S. Computer Science, May 2022",
  description2: "M.S. Microbiology and Cell Science, August 2017",
  description3: "B.S. Microbiology and Cell Science, June 2016",
  headline: "My Academic Journey",
  id: "signup",
  img: "/images/svg-3.svg",
  imgStart: false,
  lightBg: true,
  lightText: false,
  lighttextDesc: false,
  primary: false,
  topLine: "Education",
};
